cartesian_pose_controller:
  type: mars_control/CartesianPoseController
  arm_id: panda

cable_data_collector:
  type: mars_control/CableDataCollector
  arm_id: anan
  is_vertical: false 
  p_gain: -0.05
  gelsight_topic: /combined_arms/an_an/gelsight/pose
  output_topic: /cable_data_collection
