#!/usr/bin/python3

import rospy
import frankx
import tf

if __name__ == "__main__":
    rospy.init_node("frankx_tf_broadcaster")
    frame_id = rospy.get_param("~frame_id", "base_frame")
    rate = rospy.get_param("~rate", 30)
    robot_ip = rospy.get_param("~robot_ip", "192.168.0.144")

    br = tf.TransformBroadcaster()
    robot = frankx.Robot("192.168.0.144")

    r = rospy.Rate(rate)
    while not rospy.is_shutdown():
        pose = robot.current_pose()
        br.sendTransform(
            (pose.x, pose.y, pose.z),
            (pose.q_x, pose.q_y, pose.q_z, pose.q_w),
            rospy.Time.now(),
            "ee_frame", frame_id,
        )
        r.sleep()
    rospy.spin()
