#!/usr/bin/env python3
import rospy
import numpy as np
import pcl
from sensor_msgs.msg import PointCloud2,Image
import sensor_msgs.point_cloud2 as pc2
import ros_numpy

from cv_bridge import CvBridge, CvBridgeError

from detectron2_ros.msg import Result

class MaskNode:
    def __init__(self):
        self.br = CvBridge()
        self.W = rospy.get_param("realsense2_camera/infra_width")
        self.H = rospy.get_param("realsense2_camera/infra_height")
        self.mask = np.zeros((self.H,self.W)) 

        mask_topic = rospy.get_param("/mask_topic")
        color_topic = rospy.get_param("/color_topic")
        depth_topic = rospy.get_param("/depth_topic")
        masked_out_topic = rospy.get_param("/masked_out_topic")

        masked_depth_topic = depth_topic.split()[0] + '/' + masked_out_topic 
        masked_color_topic = color_topic.split()[0] + '/' + masked_out_topic 
        self.detect_sub = rospy.Subscriber(mask_topic, Result, self.detection_cb, queue_size=10)
        self.depth_sub = rospy.Subscriber(depth_topic, Image, self.depth_callback, queue_size=10)
        self.color_sub = rospy.Subscriber(color_topic, Image, self.color_callback, queue_size=10)

        self.masked_color_pub = rospy.Publisher(masked_color_topic, Image, queue_size=10)
        self.masked_depth_pub = rospy.Publisher(masked_depth_topic, Image, queue_size=10)

    def detection_cb(self,msg):
        mask = np.zeros((self.H,self.W))
        for m in msg.masks:
            m = self.br.imgmsg_to_cv2(m)
            mask = np.bitwise_or(mask, m)
        self.mask = mask 

    def depth_callback(self,msg):
        im = np.array(self.br.imgmsg_to_cv2(msg))
        im = np.bitwise_and(im,mask)
        msg.data = self.br.cv2_to_imgmsg(im).data
        self.masked_depth_pub.publish(msg)

    def color_callback(self,msg):
        im = np.array(self.br.imgmsg_to_cv2(msg))
        im = np.bitwise_and(im,mask)
        msg.data = self.br.cv2_to_imgmsg(im).data
        self.masked_color_pub.publish(msg)


if __name__ == '__main__':
    rospy.init_node('detect_mask_node')

    mask = MaskNode()

    rospy.spin()