seed: 512
dataset:
  rand_rotate: [-45,45]
  data_dir: '/home/ruppulur/catkin_ws/src/mars_ros/mars_perception/src/mars_perception/object_face_classifier/data'
  dataset_name: 'connector-male-6'
  img_dim: [64,64] # h,w
  min_features: 500  # features are defined by non-zero pixels
  faces: 2
train:
  device: 'cuda'
  epochs: 50
  lr: 0.001
  batch_size: 10
