# tf_frame_id = robot_id + postfix
base_frame_postfix: _link0
grasp_frame_postfix: _wsg_grasp_link
eef_frame_postfix: _link8

## List of all possible robot configurations 

# dual arm
combined_arms:
  robot_ids: ['pan_pan','an_an']
  planning_group: 'combined_arms'
  # Initializes the task dict--associates a task string to controller name
  task_controller_dict:
    insert: 'dual_plug_in_controller' 
    moveit: 'combined_arms_controller'

# single arm
panda:
  robot_ids: ['panda']
  planning_group: 'panda_arm'
  task_controller_dict:
    insert: 'plug_in_controller' 
    moveit: 'position_joint_trajectory_controller'
