#! /usr/bin/env python3

from copy import deepcopy

import actionlib
import numpy as np
import ros_numpy
import rosnode
import rospy
import tf
from actionlib_msgs.msg import GoalStatusArray
from franka_gripper.msg import (GraspEpsilon, HomingAction, HomingActionGoal,
                                MoveAction, MoveGoal, StopAction,
                                StopActionGoal)
from gelsight_ros.msg import GelsightFlowStamped
from geometry_msgs.msg import (Pose, PoseStamped, QuaternionStamped, Vector3,
                               Vector3Stamped)
from mars_behavior.pose_utils import (AXIS_X, AXIS_Y, AXIS_Z, get_transform,
                                      rot_from_a_to_b,
                                      rot_from_a_to_b_preserve_axis,
                                      rotate_mat_from_euler,
                                      tf_mat_to_quat_stamped, transform_vector)
from mars_msgs.msg import MoveToAction, MoveToGoal
from mars_msgs.srv import ICPMeshTF
from moveit_commander import MoveGroupCommander

class CableInsertionNode:
    base_frame_: str = rospy.get_param("base_frame")
    eef_frame_: str = rospy.get_param("eef_frame", 'panda_hand')
    grasp_frame_: str = rospy.get_param("grasp_frame", 'gelsight_pad')
    grasped_flow_norm_ = 0.0
    planning_goals_ = []
    GRASP_THRESHOLD_ = 20
    GRASP_HEIGHT_OFFSET_ = 0.2

    def __init__(self):
        self.move = actionlib.SimpleActionClient('move_to', MoveToAction)
        self.grasping = actionlib.SimpleActionClient('franka_gripper/move', MoveAction)
        self.homing = actionlib.SimpleActionClient('franka_gripper/homing', HomingAction)
        self.stop = actionlib.SimpleActionClient('franka_gripper/stop', StopAction)

        self.flow = rospy.Subscriber('flow',GelsightFlowStamped, self.flow_cb_)
        #self.debug_goal = rospy.Publisher('test_cable_eef_pose',PoseStamped,queue_size=1)

        self.icp = rospy.ServiceProxy('icp_mesh_tf',ICPMeshTF) 
        self.tf_listener = tf.TransformListener()
        self.move.wait_for_server()
        self.grasping.wait_for_server()
        self.homing.wait_for_server()
        self.stop.wait_for_server()

        home_goal = HomingActionGoal()
        self.homing.send_goal(home_goal)
        #self.homing.wait_for_result()

    def flow_cb_(self,msg: GelsightFlowStamped):
        flow_np = np.array(msg.cur_markers.data) - np.array(msg.ref_markers.data)
        flow_np = np.reshape(flow_np, (msg.cur_markers.m,msg.cur_markers.n,2))
        self.grasped_flow_norm_ = np.linalg.norm(flow_np)

    def get_object_pose_(self, mesh_name: str, ref_frame: str):
        rospy.set_param('/detect_class_names',mesh_name)
        rospy.sleep(0.1)
        self.icp(mesh_name)
        rospy.sleep(3.0)
        pose = get_transform(mesh_name + '_frame',ref_frame, self.tf_listener)
        return pose
    
    def add_goal_(self, goal : PoseStamped):
        g = deepcopy(goal)
        if g.header.frame_id != self.eef_frame_ and g.header.frame_id != self.base_frame_:
            g = self.grasp_to_eef_frame_(g)
        if g.header.frame_id != self.base_frame_:
            g = self.pose_to_base_frame_(g)
        self.planning_goals_.append(g.pose)
    
    def execute_planned_goals_(self):
        self.move.send_goal(MoveToGoal(targets=self.planning_goals_))
        self.move.wait_for_result()
        self.planning_goals_ = []


    def grasp_to_eef_frame_(self,T_GcurGnew : PoseStamped) -> PoseStamped:
        T_EG = get_transform(self.eef_frame_,self.grasp_frame_,self.tf_listener) # E - end effector, G - grasp frame
        T_EG: np.ndarray = ros_numpy.numpify(T_EG)
        T_Gcur_Gnew: np.ndarray = ros_numpy.numpify(T_GcurGnew.pose)

        new_pose = ros_numpy.msgify(Pose, np.matmul(np.linalg.inv(T_EG),np.matmul(T_Gcur_Gnew,T_EG)))
        new_pose = PoseStamped(pose=new_pose)
        new_pose.header.frame_id = self.eef_frame_
        return new_pose 

    def pose_to_base_frame_(self,pose : PoseStamped) -> PoseStamped:
        return self.tf_listener.transformPose(self.base_frame_,pose)

    def cable_pick(self):
        # Get pose of object

        rospy.loginfo("Starting cable pick")
        cable_male_pose = self.get_object_pose_('cable_male',self.grasp_frame_)
        self.grasp_pose = cable_male_pose
        hover_pose = PoseStamped() 
        hover_pose.header.frame_id = self.grasp_frame_
        hover_pose.pose = deepcopy(cable_male_pose)

        grasp_pose = PoseStamped(header=hover_pose.header) 
        grasp_pose.pose = deepcopy(cable_male_pose) 
        y_axis_cable_in_hand = transform_vector(AXIS_Y,'cable_male_frame',self.grasp_frame_,self.tf_listener)

        tf_mat = rot_from_a_to_b_preserve_axis(AXIS_X, y_axis_cable_in_hand,AXIS_Z)
            
        grasp_pose.pose.orientation = tf_mat_to_quat_stamped(tf_mat,self.grasp_frame_).quaternion
        hover_pose.pose.orientation = tf_mat_to_quat_stamped(tf_mat,self.grasp_frame_).quaternion

        hover_pose = self.pose_to_base_frame_(self.grasp_to_eef_frame_(hover_pose))
        hover_pose.pose.position.z += self.GRASP_HEIGHT_OFFSET_ 
        #self.debug_goal.publish(hover_pose)
        #self.debug_goal.publish(grasp_pose)

        self.add_goal_(hover_pose)
        self.add_goal_(grasp_pose)
        self.execute_planned_goals_()

        self.grasp()

        self.add_goal_(hover_pose)
        self.execute_planned_goals_()
    

    def go_home(self) -> None:
        # move to ready pose
        rospy.wait_for_message('move_group/status', GoalStatusArray)
        commander = MoveGroupCommander('panda_arm')
        commander.set_end_effector_link("gelsight_pad")
        commander.set_pose_reference_frame("panda_link0")
        commander.set_named_target('ready')
        commander.go(wait=True)

    def grasp(self) -> None:
        self.grasping.send_goal(MoveGoal(width=0,speed=0.02))
        rate = rospy.Rate(30)
        while self.grasped_flow_norm_ < self.GRASP_THRESHOLD_:
            rospy.loginfo("flow_norm: %4f",self.grasped_flow_norm_)
            if self.grasping.get_state() != actionlib.SimpleGoalState.PENDING and self.grasping.get_state() != actionlib.SimpleGoalState.ACTIVE:
                rospy.loginfo("MISSED DETECTION!")
                self.stop.send_goal(StopActionGoal())
                break
            if rospy.is_shutdown():
                rospy.loginfo("SHUTDOWN!")
                self.stop.send_goal(StopActionGoal())
                raise Exception("GRASP INCOMPLETE!") 
            rate.sleep()
        self.grasping.cancel_all_goals()
        self.stop.send_goal(StopActionGoal())
        rospy.loginfo("GRASP COMPLETE!")

    def cable_insert(self) -> None:
        cable_female_pose = self.get_object_pose_('cable_female',self.grasp_frame_)

        self.grasp_pose = cable_female_pose
        hover_pose = PoseStamped() 
        hover_pose.header.frame_id = self.grasp_frame_
        hover_pose.pose = deepcopy(cable_female_pose)

        aligned_pose = deepcopy(hover_pose)
        aligned_pose.pose = deepcopy(cable_female_pose)
        down_ori = transform_vector(-AXIS_Z,self.base_frame_,self.grasp_frame_,self.tf_listener)
        tf_mat = rot_from_a_to_b(-AXIS_X, down_ori)
        tf_mat = rotate_mat_from_euler([0,0,np.pi/2],tf_mat)
        hover_pose.pose.orientation = tf_mat_to_quat_stamped(tf_mat,self.grasp_frame_).quaternion
        aligned_pose.pose.orientation = tf_mat_to_quat_stamped(tf_mat,self.grasp_frame_).quaternion

        hover_pose = self.pose_to_base_frame_(self.grasp_to_eef_frame_(hover_pose))
        hover_pose.pose.position.z += self.GRASP_HEIGHT_OFFSET_ 

        self.add_goal_(hover_pose)
        #self.add_goal(aligned_pose)

        self.execute_planned_goals_()
    

if __name__ == '__main__':
    rospy.init_node('cable_insertion_node')
    insertion = CableInsertionNode()
    insertion.go_home()
    insertion.cable_pick()
    insertion.go_home()
    insertion.cable_insert()
    rospy.spin()
